server:
  port: 8080

grpc:
  client:
    employeeService:
      address: static://localhost:7071
      negotiationType: plaintext
    roomService:
      address: static://localhost:7072
      negotiationType: plaintext

spring:
  application:
    name: ReservationService

  datasource:
    url: jdbc:postgresql://localhost:5435/reservation_service
    username: reservation_user
    password: reservation_pass

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

jwt:
  secret: "Qm9zYV9zZWN1cmVfSldUX3NlY3JldF9rZXlfNTY3ODkw"


