server:
  port: 8085

spring:
  application:
    name: CalendarService

  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/calendar_mongodb?authSource=admin
      auto-index-creation: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: calendar-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          com.roomreservation.reservationservice.messaging.event.ReservationCreatedEvent:com.roomreservation.calendarservice.event.ReservationCreatedEvent,
          com.roomreservation.reservationservice.messaging.event.ReservationRoomStatusChangedEvent:com.roomreservation.calendarservice.event.ReservationRoomStatusChangedEvent

springdoc:
  default-flat-param-object: true
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
