server:
  port: 8084

spring:
  application:
    name: NotificationService

  datasource:
    url: jdbc:postgresql://localhost:5436/notification_service
    username: notif_user
    password: notif_pass

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: bc6f74d3cd56a6
    password: 69de5e76382371

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service4
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: com.roomreservation.authenticationservice.messaging.event.UserInvitedEvent:com.roomreservation.notificationservice.event.UserInvitedEvent
      auto-offset-reset: earliest

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

app:
  kafka:
    topics:
      userInvited: user-invited


