services:
  postgres:
    image: postgres:16
    container_name: room_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: room_service
      POSTGRES_USER: room_user
      POSTGRES_PASSWORD: room_pass
    ports:
      - "5434:5432"
    volumes:
      - room_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U room_user -d room_service" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  room_pg_data:
