services:
  postgres:
    image: postgres:16
    container_name: employee_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: employee_service
      POSTGRES_USER: employee_user
      POSTGRES_PASSWORD: employee_pass
    ports:
      - "5433:5432"
    volumes:
      - employee_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U employee_user -d employee_service"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  employee_pg_data:
