server:
  port: 8083

grpc:
  server:
    port: 7072
  client:
    reservationService:
      address: static://localhost:7073
      negotiationType: plaintext

spring:
  application:
    name: RoomService

  datasource:
    url: jdbc:postgresql://localhost:5434/room_service
    username: room_user
    password: room_pass

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

jwt:
  secret: "Qm9zYV9zZWN1cmVfSldUX3NlY3JldF9rZXlfNTY3ODkw"



