spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/employee_service
    username: employee_user
    password: employee_pass

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

auth:
  service-url: "http://localhost:8081"

server:
  port: 8082
